const FVC_DATA = [
  {
    "id": 1,
    "tipo": "Anual",
    "oportunidade": "Redimencionamento do time financeiro - Economia Anual",
    "negocio": "AHAV",
    "valorAno": -39800.58666666666,
    "valorMensal": -3316.715555555555,
    "referencia": "Anual",
    "competencia": "2026",
    "planoAcao": "Ajuste de estrutura do time financeiro - redução de 1 HC (sem reposição).",
    "responsavel": "Flávia",
    "status": "Concluído",
    "condicao": "Desligamento e não reposição vaga"
  },
  {
    "id": 2,
    "tipo": "Anual",
    "oportunidade": "Redimencionamento do time financeiro - Economia Anual",
    "negocio": "AHAV",
    "valorAno": -32675.376164799996,
    "valorMensal": -2722.948013733333,
    "referencia": "Anual",
    "competencia": "2026",
    "planoAcao": "Ajuste de estrutura do time financeiro - redução de 1 HC (sem reposição).",
    "responsavel": "Flávia",
    "status": "Em Andamento",
    "condicao": "Aguardar para desligamento HC"
  },
  {
    "id": 3,
    "tipo": "Anual",
    "oportunidade": "Redução HC Controladoria - Economia Anual",
    "negocio": "AHAV",
    "valorAno": -18356.04,
    "valorMensal": -1529.67,
    "referencia": "Anual",
    "competencia": "2026",
    "planoAcao": "Ajustar contrato com terceiros para o serviço de controladoria.",
    "responsavel": "Diego",
    "status": "Concluído",
    "condicao": "Negociação com novo HC ok, ajustar o contrato com fornecedor"
  },
  {
    "id": 4,
    "tipo": "Anual",
    "oportunidade": "Cancelamento Omie - Smartmold (Migração para Sankhya)",
    "negocio": "Smartmold",
    "valorAno": -9996.84,
    "valorMensal": -833.07,
    "referencia": "Anual",
    "competencia": "2026",
    "planoAcao": "Cancelamento da assinatura após a migração para o Sankhya.",
    "responsavel": "Flávia",
    "status": "Em Andamento",
    "condicao": "Aguardando migração"
  },
  {
    "id": 5,
    "tipo": "Anual",
    "oportunidade": "Seguros DF e GO -  Banco do Brasil (Cancelado)",
    "negocio": "REDE EPI",
    "valorAno": -8142.610000000001,
    "valorMensal": -678.5508333333333,
    "referencia": "Anual",
    "competencia": "2026",
    "planoAcao": "Cotação com Santander com mesmas coberturas ou superiores.",
    "responsavel": "Flávia",
    "status": "Concluído",
    "condicao": ""
  },
  {
    "id": 6,
    "tipo": "Anual",
    "oportunidade": "Trocas de SPC para Serasa (Economia 14%)",
    "negocio": "REDE EPI",
    "valorAno": -8427.295800000002,
    "valorMensal": -702.2746500000002,
    "referencia": "Anual",
    "competencia": "2026",
    "planoAcao": "Cotação e Negociação junto ao fornecedor. Fechamento do contrato e distrato com SPC.",
    "responsavel": "Diego",
    "status": "Concluído",
    "condicao": ""
  },
  {
    "id": 7,
    "tipo": "Anual",
    "oportunidade": "Tarifa Básica SPC - JP T1 e IPA (Troca para Serasa sem Tarifa Mínima)",
    "negocio": "Loteamentos",
    "valorAno": -4999.68,
    "valorMensal": -416.64,
    "referencia": "Anual",
    "competencia": "2026",
    "planoAcao": "Cancelamento junto ao SPC e vincular dentro do contrato de Rede EPI (caso tenhamos necessidade), caso o volume aumente, necociar para as SPE's.",
    "responsavel": "Diego",
    "status": "Concluído",
    "condicao": ""
  },
  {
    "id": 8,
    "tipo": "Anual",
    "oportunidade": "Tarifas de Boletos Banco Brasil (R$ 9,00 Emissão / R$ 9,00 Baixa/Emissão)",
    "negocio": "Loteamentos",
    "valorAno": -82128.0,
    "valorMensal": -6844.0,
    "referencia": "Anual",
    "competencia": "2026",
    "planoAcao": "Abertura de conta e emissão dos boletos via Santander. Negociar idem Rede EPI R$ 0,00 Emissão e R$ 0,89 Baixa/Recebimento.",
    "responsavel": "Flávia",
    "status": "Concluído",
    "condicao": ""
  },
  {
    "id": 9,
    "tipo": "Anual",
    "oportunidade": "Troca serviços de cameras + Melhoria no serviço",
    "negocio": "REDE EPI",
    "valorAno": -3153.96,
    "valorMensal": -262.83,
    "referencia": "Anual",
    "competencia": "2026",
    "planoAcao": "Negociação do contrato novo junto com o contrato atual.",
    "responsavel": "Gabriel",
    "status": "Concluído",
    "condicao": ""
  },
  {
    "id": 10,
    "tipo": "Anual",
    "oportunidade": "Atualização dos dois planos de celular TIM",
    "negocio": "REDE EPI",
    "valorAno": -6600.0,
    "valorMensal": -550.0,
    "referencia": "Anual",
    "competencia": "2026",
    "planoAcao": "Solicitar o cancelamento de um de uma das contras e transferir as linhas em uso para o outro contrato",
    "responsavel": "Flávia",
    "status": "Em Andamento",
    "condicao": "Inicia em mar/26"
  },
  {
    "id": 11,
    "tipo": "Anual",
    "oportunidade": "Atualização dos dois planos de celular TIM",
    "negocio": "AHAV",
    "valorAno": -16740.0,
    "valorMensal": -1395.0,
    "referencia": "Anual",
    "competencia": "2026",
    "planoAcao": "Solicitar o cancelamento de um de uma das contras e transferir as linhas em uso para o outro contrato",
    "responsavel": "Flávia",
    "status": "Em Andamento",
    "condicao": "Inicia em jul/26"
  },
  {
    "id": 12,
    "tipo": "Anual",
    "oportunidade": "Cancelamento Contrato Locação Impressora Telesite",
    "negocio": "Telesite",
    "valorAno": -1800.0,
    "valorMensal": -150.0,
    "referencia": "Anual",
    "competencia": "2026",
    "planoAcao": "Solicitar o cancelamento da impressora da Telesite (impressora desligada na sala onde ficava Telesite",
    "responsavel": "Flávia",
    "status": "Concluído",
    "condicao": ""
  },
  {
    "id": 13,
    "tipo": "Anual",
    "oportunidade": "Tarifa de Manutenção - Banco do Brasil",
    "negocio": "Grupo",
    "valorAno": -12698.400000000001,
    "valorMensal": -1058.2,
    "referencia": "Anual",
    "competencia": "2026",
    "planoAcao": "Solicitar o cancelamento das tarifas de pacote das 13 contas do banco do brasil e solicitar o plano com tarifas básicas",
    "responsavel": "Flávia",
    "status": "Em Andamento",
    "condicao": ""
  },
  {
    "id": 14,
    "tipo": "Anual",
    "oportunidade": "Tarifa de Manutenção - Bradesco",
    "negocio": "REDE EPI",
    "valorAno": -3741.6000000000004,
    "valorMensal": -311.8,
    "referencia": "Anual",
    "competencia": "2026",
    "planoAcao": "Solicitar o cancelamento da conta ou isenção de tarifas",
    "responsavel": "Flávia",
    "status": "Em Andamento",
    "condicao": ""
  },
  {
    "id": 15,
    "tipo": "Anual",
    "oportunidade": "Renovação Bitrix vs ARRECIFE",
    "negocio": "REDE EPI",
    "valorAno": -6879.0,
    "valorMensal": -573.25,
    "referencia": "Anual",
    "competencia": "2026",
    "planoAcao": "Solicitar a renovação do contrato valor anuidade + serviços de suporte e cancelar a cobrança do serviço de suporte pago a parte.",
    "responsavel": "Flávia",
    "status": "Concluído",
    "condicao": ""
  },
  {
    "id": 1,
    "tipo": "Pontual",
    "oportunidade": "Cobranças indevidas (renegociação de contrato) com BB. - Loteamemto Iporá",
    "negocio": "Loteamentos",
    "valorAno": -8024.3,
    "valorMensal": 0.0,
    "referencia": "Pontual",
    "competencia": "21/06/25 a 28/11/25",
    "planoAcao": "Fazer o levantamento e solicitar o estorno do Banco, ou desconto em tarifas futuras",
    "responsavel": "Flávia",
    "status": "Em Andamento",
    "condicao": "Estorno ou desconto futuro"
  },
  {
    "id": 2,
    "tipo": "Pontual",
    "oportunidade": "Cobranças indevidas (renegociação de contrato) com BB. - Loteamemto JP",
    "negocio": "Loteamentos",
    "valorAno": -12616.6,
    "valorMensal": 0.0,
    "referencia": "Pontual",
    "competencia": "21/06/25 a 28/11/25",
    "planoAcao": "Fazer o levantamento e solicitar o estorno do Banco, ou desconto em tarifas futuras",
    "responsavel": "Flávia",
    "status": "Em Andamento",
    "condicao": "Estorno ou desconto futuro"
  },
  {
    "id": 3,
    "tipo": "Pontual",
    "oportunidade": "Pagamento de ISS pra NF's com processo de cancelamento",
    "negocio": "Telesite",
    "valorAno": -10431.0,
    "valorMensal": 0.0,
    "referencia": "Pontual",
    "competencia": "2023 a 2025",
    "planoAcao": "Solicitar o cancelamento na Prefeitura para geração de créditos",
    "responsavel": "João",
    "status": "Concluído",
    "condicao": "Compensação em guias futuras"
  },
  {
    "id": 4,
    "tipo": "Pontual",
    "oportunidade": "Ajuste de distratos de contrato de locação (em andamento)",
    "negocio": "Loteamentos",
    "valorAno": 0.0,
    "valorMensal": 0.0,
    "referencia": "Pontual",
    "competencia": "",
    "planoAcao": "Ajustado os distratos em andamento e processo para os novos contratos (atualização)",
    "responsavel": "Diego",
    "status": "Em Andamento",
    "condicao": ""
  },
  {
    "id": 5,
    "tipo": "Pontual",
    "oportunidade": "Processo de liberação de juros/multa no recebimento de clientes",
    "negocio": "REDE EPI",
    "valorAno": -252653.0,
    "valorMensal": 0.0,
    "referencia": "Pontual",
    "competencia": "01/01/25 a 31/12/25",
    "planoAcao": "Criação de processo para contabilização do desconto e acompanhamento dos valores, criar alçada para liberação da isenção de multa e juros",
    "responsavel": "Mayara",
    "status": "Em Andamento",
    "condicao": "Sem retorno dos valores (legado)"
  },
  {
    "id": 6,
    "tipo": "Pontual",
    "oportunidade": "Processo de estorno no Santander (Patamar antes ~2.5k e novo dez-25 7k.",
    "negocio": "REDE EPI",
    "valorAno": -4500.0,
    "valorMensal": 0.0,
    "referencia": "Pontual",
    "competencia": "01/12/25 a 31/12/25",
    "planoAcao": "Solicitar o estorno das cobranças junto ao Santader e atualizar o contrato para não atualizar os valores (sem vencimento).",
    "responsavel": "Flávia",
    "status": "Em Andamento",
    "condicao": ""
  }
];
