const RISK_DATA = [
  {
    "id": 1,
    "item": "Nota de Débito fora do Grupo Ahav",
    "negocio": "Grupo",
    "risco": "Utilização de notas de débito entre empresas do grupo sem formalização contratual adequada.",
    "impacto": "Glosa fiscal, autuação por ausência de lastro jurídico, risco de descaracterização de despesas.",
    "mitigacao": "1. Legal Opinion para fundamentar processo\n2. Formalizar contrato de rateio intercompany\n3. Revisão tributária retroativa\n4. Implantar política formal de reembolso e rateio",
    "natureza": "Tributário",
    "criticidade": "Grave",
    "prioridade": "Alta",
    "exposicao": 793428.7407992749,
    "periodo": "Mai/22 a Jan/26",
    "status": "Em andamento",
    "obs": "24/02 - Validando parecer técnico, tributário e nova minuta com advogados e contradores para a não necessidade do pagamento de impostos."
  },
  {
    "id": 2,
    "item": "Processo manual do contas a pagar",
    "negocio": "Grupo",
    "risco": "Edição manual de títulos antes do pagamento.",
    "impacto": "Fraude, erro material, pagamento indevido.",
    "mitigacao": "1. Desenho e automatização do fluxo - ERP\n2. Bloqueio de edição após aprovação\n3. Auditoria periódica",
    "natureza": "Financeiro",
    "criticidade": "Grave",
    "prioridade": "Alta",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Em andamento",
    "obs": "25/02 - Processo de CNAE no Santander concluído com sucesso, travas sistémicas criadas."
  },
  {
    "id": 3,
    "item": "Processo de pagamentos via - DDA",
    "negocio": "Grupo",
    "risco": "Pagamentos realizados com base em boletos disponibilizados via DDA, sem vínculo obrigatório com processo interno validado no ERP.",
    "impacto": "Pagamentos fraudulentos. Perda financeira direta.",
    "mitigacao": "1. Descontinuidade do uso do DDA para liquidação\n2. Restrição de acesso ao DDA apenas para consulta\n3. Implantação de política formal de pagamentos",
    "natureza": "Financeiro",
    "criticidade": "Grave",
    "prioridade": "Alta",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Em andamento",
    "obs": "13/02 - Alinhado processo para usar somente para consulta, mesmo que ainda ativo. Validar com Santander para desativar e efetuar processo somente com remessa e retorno. "
  },
  {
    "id": 4,
    "item": "Baixas de pagamentos em entidades (CNPJ) diferentes",
    "negocio": "Rede EPI",
    "risco": "Baixa contábil em empresa distinta da obrigação.",
    "impacto": "Distorção contábil e fiscal.",
    "mitigacao": "1. Travar baixa por centro de custo/CNPJ\n2. Conciliação mensal intercompany",
    "natureza": "Financeiro",
    "criticidade": "Médio",
    "prioridade": "Média",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Em andamento",
    "obs": "24/02 - Trava do sistema valendo para todas as empresa <> Rede EPI devido ao processo do cartão de crédito que será corrigido até 01/04."
  },
  {
    "id": 5,
    "item": "Ausência de controles de compensação de adiantamentos",
    "negocio": "Grupo",
    "risco": "Adiantamentos não compensados corretamente.",
    "impacto": "Distorção patrimonial, superavaliação do ativo, ocultação de despesas não reconhecidas, risco de desvio ou uso indevido",
    "mitigacao": "1. Política formal de adiantamentos\n2. Conciliação mensal obrigatória\n3. Prazo máximo para liquidação\n4. Proibição de novos adiantamentos com saldo",
    "natureza": "Financeiro",
    "criticidade": "Grave",
    "prioridade": "Média",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Em andamento",
    "obs": "Volume relevante de adiantamentos (fornecedores, clientes, sócios) sem controle estruturado de compensação e risco de confusão patrimonial."
  },
  {
    "id": 6,
    "item": "Ausência de estudos Tributário das empresas do Grupo",
    "negocio": "Grupo",
    "risco": "Regime tributário ineficiente.",
    "impacto": "Pagamento indevido de tributos.",
    "mitigacao": "1. Planejamento tributário anual\n2. Simulação Lucro Real vs Presumido\n3. Revisão créditos fiscais",
    "natureza": "Tributário",
    "criticidade": "Grave",
    "prioridade": "Alta",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Não Iniciado",
    "obs": "Estrutura societária ineficiente para otimização tributária, podendo gerar pagamento indevido de IR/CSLL ou consumo inadequado de prejuízo fiscal."
  },
  {
    "id": 7,
    "item": "Liberação de vendas via \"Comitê\"",
    "negocio": "Rede EPI",
    "risco": "Vendas sem análise formal de crédito.",
    "impacto": "Inadimplência elevada.",
    "mitigacao": "1. Política formal de crédito\n2. Score mínimo obrigatório\n3. Registro formal em ata",
    "natureza": "Financeiro",
    "criticidade": "Grave",
    "prioridade": "Média",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Não Iniciado",
    "obs": "Liberação de vendas sem rigor na análise de crédito, impactando diretamente na inadimplência."
  },
  {
    "id": 8,
    "item": "Passivos sendo arcados por entidades distintas.",
    "negocio": "Smallsite",
    "risco": "Empresa pagando dívida de outra.",
    "impacto": "Confusão patrimonial.",
    "mitigacao": "1. Formalizar mútuo intercompany\n2. Segregação financeira rigorosa",
    "natureza": "Societário",
    "criticidade": "Grave",
    "prioridade": "Alta",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Não Iniciado",
    "obs": "Ativos da Smallsites sem lastro econômico e despesas suportadas por outra entidade, com risco societário e contábil."
  },
  {
    "id": 9,
    "item": "Passivos ocultos - Emprestimos",
    "negocio": "Smallsite",
    "risco": "Dívidas não registradas.",
    "impacto": "Risco societário e contábil.",
    "mitigacao": "1. Reconciliação bancária histórica\n2. Formalização contratual\n3. Ajuste contábil imediato",
    "natureza": "Financeiro",
    "criticidade": "Grave",
    "prioridade": "Alta",
    "exposicao": 400000.0,
    "periodo": "N/A",
    "status": "Não Iniciado",
    "obs": "Passivo bancário relevante (~R$ 400 mil) na Smallsites, com possível bloqueio judicial e impacto financeiro."
  },
  {
    "id": 10,
    "item": "Criação de estoque virtual (Conta de Controle)",
    "negocio": "Rede EPI",
    "risco": "Movimentação sem lastro físico.",
    "impacto": "Distorção de CMV e lucro.",
    "mitigacao": "1. Inventário físico\n2. Ajuste contábil",
    "natureza": "Tributário",
    "criticidade": "Médio",
    "prioridade": "",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Não Iniciado",
    "obs": "Criação de estoque virtual para ajustes sem lastro físico adequado, gerando risco de distorção no CMV e resultado."
  },
  {
    "id": 11,
    "item": "Acesso a internet bank via operador Master",
    "negocio": "Grupo",
    "risco": "Concentração de poderes bancários.",
    "impacto": "Fraude relevante.",
    "mitigacao": "1. Dupla aprovação\n2. Segregação formal",
    "natureza": "Financeiro",
    "criticidade": "Grave",
    "prioridade": "",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Não Iniciado",
    "obs": "Acesso bancário com operador master sem segregação de função e alçadas formais, elevando risco de fraude."
  },
  {
    "id": 12,
    "item": "Baixas de recebimentos e pagamentos não identificados via contas de adiantamento.",
    "negocio": "Grupo",
    "risco": "Baixas sem documentação.",
    "impacto": "Distorção patrimonial.",
    "mitigacao": "1. Conciliação mensal\n2. Política formal de comprovação",
    "natureza": "Financeiro",
    "criticidade": "Médio",
    "prioridade": "",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Não Iniciado",
    "obs": "Grande volume de adiantamentos sem encontro de contas formalizado, com risco de não compensação e distorção patrimonial."
  },
  {
    "id": 13,
    "item": "Cancelamento de boletos e recebimento via pix sem encargos financeiros",
    "negocio": "Rede EPI",
    "risco": "Recebimento fora do fluxo formal.",
    "impacto": "Descontrole financeiro.",
    "mitigacao": "1. Proibir recebimento fora do ERP\n2. Conciliação PIX automática",
    "natureza": "Financeiro",
    "criticidade": "Grave",
    "prioridade": "",
    "exposicao": 252653.0,
    "periodo": "N/A",
    "status": "Não Iniciado",
    "obs": "Baixa de boletos via PIX sem travas e alçadas de aprovação, com risco operacional e financeiro."
  },
  {
    "id": 14,
    "item": "Pagamento de Comissão - Loteamentos",
    "negocio": "Loteamentos",
    "risco": "Pagamento antecipado sem meta formal.",
    "impacto": "Perda financeira futura.",
    "mitigacao": "1. Comissão condicionada a recebimento\n2. Cláusula de clawback",
    "natureza": "Financeiro",
    "criticidade": "Médio",
    "prioridade": "",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Não Iniciado",
    "obs": "Pagamento de comissões sem mecanismo de proteção contra distratos futuros, gerando risco de perda financeira."
  },
  {
    "id": 15,
    "item": "Risco Trabalhista - RPAs (Smartmold)",
    "negocio": "Smartmold",
    "risco": "Reconhecimento de vínculo.",
    "impacto": "Passivo retroativo relevante.",
    "mitigacao": "1. Revisão jurídica\n2. Migração modelo contratação",
    "natureza": "Trabalhista",
    "criticidade": "Grave",
    "prioridade": "",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Não Iniciado",
    "obs": "Contratação recorrente via RPA com risco previdenciário e reconhecimento de vínculo empregatício."
  },
  {
    "id": 16,
    "item": "Passivos de Lucros a distribuir no passivo",
    "negocio": "TS Imob.",
    "risco": "Registro indevido no passivo.",
    "impacto": "Distorção patrimonial.",
    "mitigacao": "1. Revisão societária\n2. Ajuste conforme contrato social",
    "natureza": "Societário",
    "criticidade": "Médio",
    "prioridade": "",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Não Iniciado",
    "obs": "Lucros não distribuídos registrados no passivo envolvendo sócios retirados, com necessidade de regularização societária."
  },
  {
    "id": 17,
    "item": "Ausência de registros de compra e venda no ativo da SPE",
    "negocio": "SPE JP-T2",
    "risco": "Ganho de capital não reconhecido.",
    "impacto": "Risco tributário e societário.",
    "mitigacao": "1. Levantamento histórico\n2. Ajuste contábil\n3. Ata formal",
    "natureza": "Societário",
    "criticidade": "Grave",
    "prioridade": "",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Em andamento",
    "obs": "Ausência de registro adequado de atos societários e operações na SPE JP-T2, com impacto no ganho de capital e PL."
  },
  {
    "id": 18,
    "item": "Gestão de Benefícios",
    "negocio": "Grupo",
    "risco": "Pagamento indevido a ex-funcionários.",
    "impacto": "Despesa desnecessária.",
    "mitigacao": "1. Integração DP + Financeiro\n2. Checklist desligamento",
    "natureza": "Financeiro",
    "criticidade": "Médio",
    "prioridade": "",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Não Iniciado",
    "obs": "Falta de controle na gestão de benefícios e desligamentos, gerando pagamentos indevidos a ex-colaboradores."
  },
  {
    "id": 19,
    "item": "Passivos RJ - Cronograma de Pagamentos",
    "negocio": "Rede EPI / Telesite",
    "risco": "Falta de programação sistemática.",
    "impacto": "Pressão de caixa futura.",
    "mitigacao": "Cronograma financeiro estruturado",
    "natureza": "Financeiro",
    "criticidade": "Baixo",
    "prioridade": "",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Não Iniciado",
    "obs": "Ausência de cronograma financeiro estruturado para passivos da RJ, com risco de pressão de caixa e acionamento judicial."
  },
  {
    "id": 20,
    "item": "Processos Trabalhistas - Provisão de Perda (Possível/Provável)",
    "negocio": "Telesite",
    "risco": "Subprovisionamento.",
    "impacto": "Surpresa financeira.",
    "mitigacao": "1. Revisão jurídica trimestral\n2. Ajuste CPC 25",
    "natureza": "Trabalhista",
    "criticidade": "Médio",
    "prioridade": "",
    "exposicao": 261638.05,
    "periodo": "N/A",
    "status": "Em andamento",
    "obs": "Processos trabalhistas com risco provável e possível de perda (~R$ 261 mil), exigindo acompanhamento e provisão adequada."
  },
  {
    "id": 21,
    "item": "Confusão Patrimonial - Ativos em entidades diferentes",
    "negocio": "Grupo",
    "risco": "Mistura de ativos entre empresas.",
    "impacto": "Desconsideração da personalidade jurídica.",
    "mitigacao": "1. Segregação formal\n2. Controle patrimonial por CNPJ",
    "natureza": "Societário",
    "criticidade": "Grave",
    "prioridade": "",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Não Iniciado",
    "obs": "Ativos imobilizados alocados em entidades sem geração de benefício econômico futuro, gerando distorção patrimonial."
  },
  {
    "id": 22,
    "item": "Operações entre partes relacionadas",
    "negocio": "Grupo",
    "risco": "Falta de contrato formal.",
    "impacto": "Questionamento fiscal.",
    "mitigacao": "1. Política formal2. \nContrato intercompany",
    "natureza": "Societário",
    "criticidade": "Médio",
    "prioridade": "",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Não Iniciado",
    "obs": "Movimentações relevantes de caixa entre empresas do grupo e partes relacionadas, com risco de desproporcionalidade societária."
  },
  {
    "id": 23,
    "item": "Parcelamento / Não pagamentos de impostos",
    "negocio": "Grupo",
    "risco": "Débitos recorrentes.",
    "impacto": "Multas, bloqueios judiciais.",
    "mitigacao": "1. Diagnóstico completo\n2. Política fiscal preventiva",
    "natureza": "Tributário",
    "criticidade": "Grave",
    "prioridade": "",
    "exposicao": 0.0,
    "periodo": "N/A",
    "status": "Em andamento",
    "obs": "Indícios de direcionamento para não pagamento ou parcelamento recorrente de tributos, com risco fiscal relevante."
  }
];
